### ISSUE TITLE
Format of input files

### ISSUE THREAD

**Issue by sidsvash26** [mrmechko/project1#3]
The input file in input/templates.txt contains the following lines:

(eat :AGENT bat :AFFECTED date)
(run :AGENT he :AFFECTED machine)

But code/test.py mentions that for "def test_file" the input format should be as follows:
"The input file will contain a JSON list of semantic templates."

The input file (input/templates.txt ) is NOT a JSON list of semantic templates but simply a bracketed list per line. Could you please correct the format in the input file so that it matches with what is required as per the definition of "test_file" function in code/test.py

Same goes for output/templates.txt. It doesn't match the format requirement as per the code/test.py file.

**Comment by mrmechko** [comment]
Added the sample json files.  I should have actually specified the input/output to come in lisp format (what is in the text files) because that is its native format.  I'll accept either, no need to change your code if you've already matched the examples.
