### ISSUE TITLE
Typo in /output/templates.txt ?

### ISSUE THREAD

**Issue by sidsvash26** [mrmechko/project1#4]
The second line of the above file is:

(EXECUTE :AGENT PERSON :AFFECTED MACHINE), (GOVERNING :AGENT PERSON :AFFECTED MACHINE)

The Agent should be "MALE-PERSON" and not PERSON as per the lexicon of "he". So the correct line should be:
(EXECUTE :AGENT MALE-PERSON :AFFECTED MACHINE), (GOVERNING :AGENT MALE-PERSON :AFFECTED MACHINE)

Let me know if this is incorrect.

**Comment by mrmechko** [comment]
corrected
