### ISSUE TITLE
Why is this not a Correct solution?

### ISSUE THREAD

**Issue by sidsvash26** [mrmechko/project1#5]
For the input:
(run :AGENT he :AFFECTED machine)

Why is the following not a correct solution?
(MOVE-RAPIDLY :AGENT MALE-PERSON :AFFECTED MACHINE) 

Move-rapidly has both "agent" and "affected" as its roles.  The agent role has no restrictions so it can take anything and affected role has "computer" as one of the restrictions which is indeed a "machine". So why does this type not qualify as an answer?

**Comment by mrmechko** [comment]
That is a valid solution.  Didn't think of it when I was writing the example.

**Comment by mrmechko** [comment]
We both did that backwards.  A `computer` is a `machine`, but a `machine` is not a `computer`
