### ISSUE TITLE
Format inconsistency in data/ontology.json

### ISSUE THREAD

**Issue by sidsvash26** [mrmechko/project1#6]
There seems to be a format inconsistency in the ontology.json file.

For the node: "name": "GOVERNING" and its "role": "AFFECTED",
"restrictions" is a nested list.
whereas in all other cases, "restrictions" is just a list.

This is causing problems in fetching data.

**Comment by mrmechko** [comment]
There should actually be several nodes in the ontology where a single role has multiple possible restrictions.  Read those as "OR" conditions.

**Comment by sidsvash26** [comment]
What's the difference between the below two restrictions : 

1. "restrictions": [
          "ABSTRACT-OBJECT",
          "SITUATION-ROOT",
          "PHYS-OBJECT"
        ]

2. "restrictions": [
          [
            "?",
            "TYP",
            "DEVICE",
            "LOCATED-EVENT",
            "MOLECULAR-PART"
          ]
        ]

The first one mentions multiple nodes separated by commas in one list which I read as "OR" but the second one has a nested list which doesn't make sense to me. Also, it has a node "?" which is not available in the Ontology.

**Comment by mrmechko** [comment]
oh I see.  We automatically simplified and preprocessed the lisp files and transformed them into `json`.  

1. this one has loose restrictions which, once you resolve the feature values, mean that any of those three types can satisfy the role.  However, there is only one restriction.  

2. On the other hand, `(?typ *restr1* *restr2* *restr3*)` indicates that there are three different sets of restrictions, which individually resolve to `ONT::DEVICE`, `ONT::LOCATED-EVENT`, and `ONT::MOLECULAR-PART`.

There are 166 instances of xor restrictions in the data.

**Comment by sayudhroy** [comment]
In this case, is this following approach okay:

In the case where we encounter a list of lists as restrictions, like in the second example mentioned above, we just flatten the list, and resolve all items in the inner lists to items in the main list i.e. we transform a list of restrictions like:

[[ "abc", "def"], ["ghi", jkl"]], to:
[ "abc", "def", "ghi", jkl"] and just ignore the "?" and "typ" whenever we encounter it?

**Comment by mrmechko** [comment]
> [[ "abc", "def"], ["ghi", jkl"]], to:
> [ "abc", "def", "ghi", jkl"] and just ignore the "?" and "typ" whenever we encounter it?

You can do this: - the name isn't `typ` for all of them.  I'll send this out via email too.

```
# the list of argument restrictions is restrs

if restrs and type(restrs[0]) is list: # if the list is not empty and the first element is a list
    restrs = restrs[0][2:] # take the rest of the list starting from index 2
```
