### ISSUE TITLE
Loading Ontology and Lexicon

### ISSUE THREAD

**Issue by sayudhroy** [mrmechko/project1#7]
Since you have mentioned in code.py that you will be running the method 'test_file' in the following manner:

`python -c "from code.test import test_file; test_file('inputfile', 'outputfile');"`

Should we call the scripts which stores the lexicon and the ontologies within that method? For the method to run correctly, the lexicon and the ontology needs to be available in memory. For that the scripts ontology.py and lexicon.py (to load the lexicon from the data), needs to be first executed. So should we call those scripts inside 'test_file'?

**Comment by sidsvash26** [comment]
I am also not clear on this. I have a python file named "functions.py" and I currently run that file to load all functions and global variables (like lex and ont) in memory and then only I can call my test_file to generate the corresponding output files. This won't work if you call each function individually from the test_file as Rik has specified. Some clarity on this would be helpful.

**Comment by mrmechko** [comment]
I'm assuming the code that you will use to load the ontology and lexicon will be executed within each testing function.  If you import whatever other code you write into `code/test.py` it should work just fine.  Whatever function calls you are making to load the ontology and lexicon can simply be run at the top of `code/test.py` after imports and before function definitions.

**Comment by mrmechko** [comment]
Also, to be clear, I was intending to run each of the functions in `code/test.py` independently.  The manner in which I call them would be using `python -c ...`

If for any reason this places an enormous burden on you, make sure to give a reason and instructions on how to get the code to run the requisite tests
