### ISSUE TITLE
Order of Output

### ISSUE THREAD

**Issue by sayudhroy** [mrmechko/project1#8]
Does the order of roles in which the JSON is generated matter? For example, in your sample output, you have given the following:
{"root": "CONSUME",  "AGENT": "NONHUMAN-ANIMAL", "AFFECTED": "FRUIT"}

Is it okay if instead of the above the output for the same is:
{"AFFECTED": "FRUIT", "AGENT": "NONHUMAN-ANIMAL", "root": "CONSUME"}?

Note that instead of the order being root, agent, affected; the order is now affected, agent, root. Since it's a dictionary, we do not have control over the order unless specifically writing code to make it that way? Is that necessary?

**Comment by mrmechko** [comment]
Order does not matter in the JSON format at all.  In S-expression format the root must come first (since it is not keyed), but the remainder can be in any order.
