### ISSUE TITLE
input confusion

### ISSUE THREAD

**Issue by yzhaoinuw** [mrmechko/project1#9]
In test.py, the comments in the header say (about the test file) "It should run with the following command `python -c "from code.test import test_file; test_file('inputfile', 'outputfile');"' "
for this input file, is it a file for subsumption_tests or for tagging_tests? Or is our code expected to detect what type of input file it is? For example, if the lines in the input file look like

person nonhuman-animal

then test_file should call subsumption_test function, and if the file has lines such as 

(eat :AGENT bat :AFFECTED date)

then test_file should call tagging_test function? 
What is the idea here?

**Comment by mrmechko** [comment]
Apologies for the confusion.  I will call each of those 3 functions separately.  `test_file` should be able to deal with semantic templates, `subsumption_tests` should be able to deal with pairs of ontology types, and `tagging_tests` should be able to deal with words.

**Comment by yzhaoinuw** [comment]
Great, thanks for the clarification.
